### ISSUE TITLE
Icons and Traits

### ISSUE THREAD

**Issue by WyntherKnight** [superseva/fallout#10]
Hi again, 

Thanks for fixing the Books and Magazines bug. Foundry still has the system on ver 1.21. Can't wait for ver 1.4 to be available.

Is it possible to make the icons appear for the Perks section and the Gear tab (Consumables, Books and Magazines, Miscellany and Unsorted) of the character sheet? Just like for Weapons and Apparel tab.

Can you also add another area in the Abilities tab for the Origin Traits (like somewhere above the Perks area). At the moment, we just create a "trait" item using the perk category, add it on the perk list but just add "Trait" on the item name.

Also to add, actors tokens resource setting changes when taken out of a compendium. I set the resource bar 1 to "health" of an actor (character or creature) and it does show it while in the compendium, but resets to "none" when taken out of the compendium.

Thanks!

**Comment by superseva** [comment]
Sure, I look in to it. The thing about icons is available space on the
sheets but I'll play with it. I am in the process if a big move (eu to USA)
ATM so I can't do it right now.
As for the update 1.4 you can always uninstall and install fallout
manually. That should pick it up. I see Forge did registered the 1.4 so
it's a bit strange Foundry is not showing the new version

**Comment by WyntherKnight** [comment]
Thanks! Uninstall and reinstall worked. Have a safe trip!
