### ISSUE TITLE
Suggestion: Ammo check and expended rounds when rolling weapon skill.

### ISSUE THREAD

**Issue by theMagius0** [superseva/fallout#18]
I'm working on possible modifications to your code with respect to ammunition.

The algorithm would check to see if the user has the ammo type listed on the weapon item when they attempt to roll their weapon skill.  

- If the ammo type field is blank, nothing happens.  (i.e. it's a melee weapon, or the GM didn't specify the field when creating the item)  
- Else, if it's listed, check that there are enough rounds remaining.  
- If there are not enough rounds (or they don't have the ammo type required), prevent the weapon skill dialog from appearing and warn the player with a dialog.  
- Else show the weapon roll dialog.  
- If they cancel the dialog, nothing happens.  
- If they roll their weapon skill, subtract the number of rounds their weapon uses from the specific ammo quantity in their inventory.

As best I can tell, its possible to modify the actor-sheet.mjs file in the ROLL WEAPON SKILL section to code most of this logic:

- item.data.data.ammo to find the ammo type for the weapon being shot
- item.data.data.ammoPerShot to find out how much ammo would be expended upon shooting
- item.actor.items.find((i) => i.name == item.data.data.ammo) to determine whether the character has the ammo on their sheet or not

I have written code to decrement ammo on the character sheet by item.data.data.ammoPerShot quantity once fired.  But, because the Dialog2d20 code is called asynchronously, there doesn't seem to be a place in the code where I could actually decrement the ammo on the character sheet in the proper sequence of events after the player clicks the ROLL button on the dialog.

Any idea where this last part of my logic would be placed in your code?

**Comment by theMagius0** [comment]
I've got the function added to DialogD6.  And it works fine when initially selecting weapon damage from the character sheet--which calls game.fallout.DialogD6.createDialog().

However, I'm baffled on how to get ammo item information passed to the game.fallout.DialogD6.createDialog() call in fallout.mjs in the renderChatMessage hook code for when the addBtn is clicked.  Mostly because I can't log anything to the console in this event handler code.  Any ideas how to peer into the "message, html, data" input parameters without using console logging here?

**Comment by superseva** [comment]
You can find message by ID and then have the message object inspected for what you need.
You can use the message flags object too.  When the message is created I am already adding some things to the flags object, so you should be able to add "ammo_id" as an optional parameter too. Later you can inspect that object for custom data.
you can access message html by either finding message by id or you can use jquery to look for the parent of "Add Button". I think messages have  their id as data-attribute in html.

**Comment by theMagius0** [comment]
So, I'm wondering if a debugging session over Discord might be a better way to go for all of these questions, but...

Is there any reason that passing an object via the chatData.flags field of Roller2D20.sendD6ToChat() would strip/remove the outer object from a class?

Because, when I'm checking the integrity of the data fallout.mjs ---> Hooks.on('renderChatMessage') ---> addBtn.click(), I'm seeing that the JS Object I'm passing via the chatData has summarily stripped the outer Object, and now it contains only the inner Object.  

This causes a stackdump because the data I'm referencing at the Roller2D20 layer is accessed via a ".data.data.ammo" path.  Whereas, the data referenced at the addBtn.click() event is accessed via a ".data.ammo" path.

I'm not a JS expert, but in the other languages I've coded in, passing by reference retains the Object structure unless you de-reference hierarchically into the inner Object layer.

Help?

**Comment by superseva** [comment]
Are you sending data object directly from the document ?
I would rather construct my own object with only the properties I need as first children of parent object. I would be mindful of object depth and all the object cloning Foundry does.
so I would rather construct something like
{
ammo:data.data.ammo.id,
weapon:data.weapon._id,
ownerId:uiser._id
}
and pass that, then actually send document object it self.

feel free to ping me on discord too.
shteff#8724

**Comment by theMagius0** [comment]
Makes sense, as the object behavior seems to be...unreliable when passed between classes.

I'll give your suggestion a try.

Thx,

**Comment by theMagius0** [comment]
Good afternoon, @superseva.

I've got the ammo decrement working, and I'm messing around with dialogs to notify the player that they are out of ammo.

Two Questions for you:

1. Is there a "trick" to getting the Dialog height to correctly display a PNG/WEBP image the first time it's shown?  (After the first time, everything is displayed correctly.)

2. I'm testing my development by modifying the *.js and *.mjs files, ZIPping them up, and uploading to the Forge.  I've noticed an odd "quirk" whereby I attempt to create a new character (note: not really needed for testing ammo consumption, but trying to regression test anyway...) and I'm seeing "TypeError: game.packs.get(...) is undefined".  The oddest part about this is that your original code (unmodified by me) uses this exact same code in actor.mjs.  Have you ever encountered this error before?

Thx,

**Comment by superseva** [comment]
Nice!

1. I am not sure about the first one. There might be a parameter to be passed in Dialog Creation.
new Dialog(data, options{opt}). 
I think the DialogOptions object you re passing inherits the ApplicationOption and there is a height property there. 
check the API for that
https://foundryvtt.com/api/Dialog.html
https://foundryvtt.com/api/global.html#ApplicationOptions
But I am not sure, you'll need to play with that.

2. Hmm, sounds you haven't uploaded the packages (compendiums) that also comes with the system. There should be one that contains the skills and it is used on character creation.

**Comment by theMagius0** [comment]
FYI: Just sent a friend invite on Discord.

Thx,

**Comment by theMagius0** [comment]
Good afternoon, @superseva.

You'd mentioned adding a "fork" to this code for the ammunition counter.

I'm not very skilled with GIT, so I was wondering if you could point me in the direction of how to do that?

Thx,

**Comment by superseva** [comment]
Hey there,
I am not a git expert but what you should do is create a "fork" ( duplicate my code to your repositories).
There is a button 'fork" in the upper right corner of the fallout github project.
If you click it it will create a fork under your username
so original code will stay under "superseva/fallout" on git
and your fork will be "theMagius0/fallout".

After that you want to pull that project to your machine. I suggest using Visual Studio Code as editor so it would be easier to pull/commit/push code from and to git.

Once you have pulled your git fallout repository on your computer you want to tell foundry where to look for it. You should navigate to the systems folder of Foundry and use symbolic links (create a shortcut to the folder you are keeping your fallout code in)
on windows you can open command terminal under "systems" folder and type 
```mklink /D fallout C:\MyFoundryFalloutCode\fallout```
ofcourse you should replace the last part of the command with the proper path to your fallout folder from git
this way as soon as you make some changes to the code Foundry will know where to look. The fallout folder in Foundry/systems will have an shortcut arrow icon.

here is more about forking
https://docs.github.com/en/get-started/quickstart/fork-a-repo
you can basically skip all the terminal commands from these examples if you use Visual Studio Code

The good thing with this is that if I make some changes in the original code you can pull them to your code. (ofc you'll see if I am touching the same part of the code as you are and you'll be able to decide do you want mine or yours part), and also you can create pull request back to me so I might include your code in to the original

**Comment by theMagius0** [comment]
Thank you for all your help, sir.

My additions/modifications are now in **theMagius0/fallout** fork.

I'll close this Suggestion.
