### ISSUE TITLE
Item quantity

### ISSUE THREAD

**Issue by JRMRT** [superseva/fallout#2]
Is it possible to make do : calculate the Weight multiplied by the quantity of the item? Would like to see item icon and their quantity in the gear inventory too

Great job for this system by the way. The character sheet look like a PIP-BOY so Nice.

**Comment by superseva** [comment]
Yeah. I plan some updates as soon as I get back to my computer next week. I'll add a task to the project list

**Comment by superseva** [comment]
this now works and you can also put float as a Weight value
