### ISSUE TITLE
Weapons rolls do not take skills into account

### ISSUE THREAD

**Issue by craftykobold** [superseva/fallout#22]
(As it is my first issue here, first of all, thanks for the great system)
When making a roll from a weapon in the inventory, the related skill is not taken into account and "skill" value is always 0.
It would be very convenient to have the related skill automatically filled in the form.

**Comment by superseva** [comment]
I can't reproduce this problem. Do you have any errors in the console ? press f12 to see the developer console. Errors should be red

**Comment by superseva** [comment]
If the skill has some value to it it should be passed to the roller window. Without any errors I am not sure where to look
