### ISSUE TITLE
Suggestion : Add damage localisation roll when rolling from a weapon

### ISSUE THREAD

**Issue by craftykobold** [superseva/fallout#23]
Quality of life feature to avoid rolling an additional d20.

When rolling from a weapon in the inventory, allow the user to also roll for damage localisation (could be a checkbox to enable/disable it when using or not this rule, or when the character is targeting a specific body part)

**Comment by superseva** [comment]
Do you mean "hit location" ?
there was a special d20 but it was removed from the roll.
Now with creature locations added I might bring it back

**Comment by superseva** [comment]
added a new die type. ID = "h"
It is rolled together with the weapon attach
check v9.0.3 and changelog here
https://github.com/superseva/fallout/blob/main/CHANGELOG.md
