### ISSUE TITLE
Feature Request: Show Item in Chat

### ISSUE THREAD

**Issue by Havoclivekiller** [superseva/fallout#27]
Whenever you click on an item on the sheet (Perk, Weapon, Armor, Gear, etc.) show it in the chat. So people could read the description (especially the GM wanting to quickly see what Perk, Gear someone is mentioning).

Bonus. Show the Item image. As of now, there is no point in adding images for Weapons if they never show up in the chat.

**Comment by superseva** [comment]
Good news: I started doing that and if you look at items.js or item-sheet header you'll see commented part of the script for that

Bad News: It is so time consuming going through all items properties once again and formatting them for the chat and with the upcoming changes to foundry 10 that will break everything and with no support from  Modiphius ... I was like " what am I doing with my free time" ;)
I'll probably get back to it when I finish making all the changes that are required for system to work under Foundry 10

**Comment by superseva** [comment]
I have done the rudimentary thing for now
v9.0.5
I'll improve on it later
On Item Sheet there is a chat bubble icon next to item's name
