### ISSUE TITLE
Feature Request: Add # of effects to damage for vicious weapons

### ISSUE THREAD

**Issue by Keladryel** [superseva/fallout#29]
Hi,

We noticed that for a total Damage in the damage rolls is not accurate in case of vicious weapons, as it does not account for effects rolled with each effect adding +1 to the damage.
It would be nice if a weapon with the vicious quality would display the total damage including the additional damage.

> Current Behavior for case of vicious weapon:
> Damage: {{damage}} | Effects: {{effects}}
> 
> Expected
> Damage: {{damage}} | Effects: {{effects}}

There are of course also other improvements that could be done like totaling up each effect (i.e. 3x Effect for Piercing 1 to show a summarized Piercing 3) to remove human factor from most of the damage/effect calculation but I did notice the most common mistake was vicious being forgotten when reading the damage. So that one would be nicest to have a little change for.

Cheers,
Keladryel

**Comment by superseva** [comment]
I will probably do the combat overhaul in the future that will take in to the consideration such things as damage effects, target’s resistances, ammo reduction, etc. At the moment I don’t include or take in the account any “modifiers/effects” when reading the dice rolled. It was just out of scope for the system release. Unfortunately I can’t do any of it before September but I’ll leave the issue open to remind me.

**Comment by superseva** [comment]
Vicious add to total dmg calculation
