### ISSUE TITLE
Bug/Feature: Item descriptions do not show the correct link

### ISSUE THREAD

**Issue by Havoclivekiller** [superseva/fallout#30]
When you open a description, any link (like this to a journal in a compedium) should be turned into Foundry links.
![image](https://user-images.githubusercontent.com/21118924/177306809-21754b0d-6428-4008-8eab-be1db25c42a6.png)
Like in this picture (don't mind the strange colors, we are using Alien RPG UI)
![image](https://user-images.githubusercontent.com/21118924/177306997-1af819c6-23c0-453c-8450-4084b14e1738.png)

**Comment by superseva** [comment]
Hmm, this should be working. Maybe style got in the way. Can you try selecting the text (link part) and click the button that clears all style in editor toolbar. I am without my computer until August unfortunately.

**Comment by Havoclivekiller** [comment]
Happens on a fresh world (no modules) too. Just create a new NPC/Creature, add Special Ability, edit and drag one of the skills.
![image](https://user-images.githubusercontent.com/21118924/177475225-8f882070-8d29-4299-ba3a-944a26ec1d1e.png)

**Comment by superseva** [comment]
I'll check it once I am back from vacation. Unfortunately not before August

**Comment by superseva** [comment]
I fixed this for Foundry v 10. I’ll release it as soon as Foundry v10 comes out
