### ISSUE TITLE
Armor DR and Power Armor Health from Worn armor not reflected under Status anymore

### ISSUE THREAD

**Issue by apostate9** [superseva/fallout#34]
![Screenshot from 2022-10-28 20-34-29](https://user-images.githubusercontent.com/45050218/198780563-960bab7e-251c-4bbe-95ed-c252d4f3288f.png)

Armor with the "shirt" icon lit, no longer adds DR to the body part under status. Using Foundry 10, latest Fallout.

**Comment by superseva** [comment]
Fallout is not updated for Foundry 10
