### ISSUE TITLE
With Foundry 10.x ADD button for additional damage dice intermittently not working

### ISSUE THREAD

**Issue by apostate9** [superseva/fallout#35]
Clicking the ADD button on a attack result will pop up the roller, but after selecting the number of dice, no dice are rolled. Happens ~90% of the time.

**Comment by superseva** [comment]
Fallout is not v10 compatible yet. I stopped updating it half way through

**Comment by apostate9** [comment]
Uh oh. Well I really screwed up here. 

Is it planned to support V10?

**Comment by superseva** [comment]
I should probably muster my strength to finish it this or the next week probably

**Comment by apostate9** [comment]
That would be most appreciated!
