### ISSUE TITLE
Bug: Journal Notes' images are borked

### ISSUE THREAD

**Issue by Havoclivekiller** [superseva/fallout#39]
Either migration or how journal notes are handled is borked. Migrated my world to v10 and the images in journal notes do not work and can't edit them, but the thumbnail module shows that they are still there.

**Comment by Havoclivekiller** [comment]
Screen of how it looks with no modules active
![image](https://user-images.githubusercontent.com/21118924/201602358-5f09ea71-51a0-4b94-bddf-2e0d440f4c36.png)
And here shows that there is an image there
![image](https://user-images.githubusercontent.com/21118924/201602482-e9d7c16a-802d-4f1f-8862-b7f91089ac16.png)

**Comment by superseva** [comment]
is that some mod interference ?
