### ISSUE TITLE
Questions about macros

### ISSUE THREAD

**Issue by Mottie1982** [superseva/fallout#41]
Hi! I need your help.
What script should I write if I want to register the damage rolls of my favorite weapon in the macro hotbar?

```
const attacker = canvas.tokens.controlled[0];
for (const item of attacker.actor.data.items) {
  if (item.system.favorite === true) {
   const num9 = item.system.damage.rating
   game.fallout.DialogD6.createDialog({diceNum:num9})
  }
}
```

In the above script, the damage of the favorite weapon can be rolled, but the damage effects are not reflected.

**Comment by superseva** [comment]
you should look at actor-sheet.mjs file
line 522
``` html.find('.weapon-roll-damage').click((ev) => {
      const li = $(ev.currentTarget).parents('.item')
      const item = this.actor.items.get(li.data('item-id'))
      let numOfDice = parseInt(item.system.damage.rating)
      if (
        item.system.weaponType == 'meleeWeapons' ||
        item.system.weaponType == 'unarmed'
      ) {
        let dmgBonus = this.actor.system?.meleeDamage?.base ?? 0
        numOfDice += dmgBonus
      }
      let rollName = item.name;
      game.fallout.DialogD6.createDialog({
        rollName: rollName,
        diceNum: numOfDice,
        weapon: item.toObject(),
      })
    }) ```
So to actually roll damage you'll need to check if melee bonuses applies from the token's actor and then also send the item as object to the roller so the effects can be picked up.
You'll also need to take in consideration multiple weapons can be marked as favorite, so you should either pick the first in the list or somehow provide a way to select one you want.

**Comment by superseva** [comment]
you can just add item as object to the macro you have
```
const attacker = canvas.tokens.controlled[0];
for (const item of attacker.actor.data.items) {
  if (item.system.favorite === true) {
   const num9 = item.system.damage.rating
   game.fallout.DialogD6.createDialog({diceNum:num9, weapon: item.toObject()})
  }
}
```
but that will till leaves out the melee bonus dmg for melee weapons, and it will only work for one item in the fav list

**Comment by Mottie1982** [comment]
Yes! Yes!! Awsome! You are really smart.
I hope lots of people use this mod!
And I appreciate your quick reply.

**Comment by superseva** [comment]
I am glad it works.

**Comment by Mottie1982** [comment]
Hey there. I need some help.

```let gmAP = game.settings.get('fallout', 'gmAP');
gmAP -= 10;
game.settings.set('fallout', 'gmAP', gmAP);
ui.notifications.info(`I have spent 10 Game Master AP. The current AP is ${gmAP}.`);```

When I use this macro, it seems that the Game Master AP is being changed correctly in the backend, but there's no change being reflected on the screen. When I tried to increase it by 1 by clicking on the screen, it actually decreased by 9 instead.

Is there any way to fix this issue?

**Comment by Mottie1982** [comment]
Hey there. I need some help.

let gmAP = game.settings.get('fallout', 'gmAP');
gmAP -= 10;
game.settings.set('fallout', 'gmAP', gmAP);
ui.notifications.info(`I have spent 10 Game Master AP. The current AP is ${gmAP}.`);

When I use this macro, it seems that the Game Master AP is being changed correctly in the backend, but there's no change being reflected on the screen. When I tried to increase it by 1 by clicking on the screen, it actually decreased by 9 instead.

Is there any way to fix this issue?

**Comment by superseva** [comment]
I will probably need to expose APTracker class so you could do just 
`game.fallout.APTracker.setAP("gmAP", 10)`
I'll push that in the next update

**Comment by superseva** [comment]
update to version 10.1.4
you can now use
`await game.fallout.APTracker.setAP("gmAP", 10)`
or
`await game.fallout.APTracker.setAP("partyAP", 10)`
to set it to some custom value

**Comment by Mottie1982** [comment]
Wow! It’s great!
Thank you so, so much!

**Comment by Mottie1982** [comment]
[ja.zip](https://github.com/superseva/fallout/files/11084872/ja.zip)
I am attaching the Japanese translation data. However, please do not misunderstand that I am strongly requesting Japanese support. If it is just for me, I have already provided the game to my friends by editing it to "en.jp". While I believe that many people should use this wonderful MOD, I do not want to cause you any trouble by doing so.
