### ISSUE TITLE
Feature Request: Reduce Max HP by Radiation

### ISSUE THREAD

**Issue by HigginsTheRed** [superseva/fallout#54]
Would love to see something where if an actor has taken radiation damage it lowers the MaxHP as well. I've been trying to do this with Active Effects but haven't been able to get it working yet.

**Comment by superseva** [comment]
Unfortunately I don't believe I can implement this and be 100% satisfy how it works since Max health field needs to be open for manual input.
I can't display the value modified by radiation and at the same time leave it open to manual input
