### ISSUE TITLE
Creature statblocks have no radiation counter

### ISSUE THREAD

**Issue by BlubberNibble** [superseva/fallout#68]
Recently I was playing in Fallout 2d20 campaign when a Ghoul attacked Dogmeat, dealing Radiation damage. It was then I realized that the biological hazard icon was for poison resistance and not a radiation tracker. Would it be possible to add a field keeping track of how much radiation damage a creature has taken?
![image](https://github.com/superseva/fallout/assets/115412663/17cef290-6750-4712-91bd-e3ab6ca5948a)

**Comment by superseva** [comment]
NPC/Creature sheets are made to represent statblocks from the book.
I am on vacation ‘til Augus. I’ll do some refactoring when I am back so I will consider it. Until then you can use data tab to keep the track , or XP filed ;)
