### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by bb46003** [superseva/fallout#69]
Hi Guys, 

i made polish transaltion of main en.json file, can you add it to system ?
[pl.zip](https://github.com/superseva/fallout/files/12560700/pl.zip)

**Comment by bb46003** [comment]
as well if you change in actor-skill.htmsl this line :
 ` <h4><a class="color-secondary"><span class="resource-label upperC">{{item.name}}</span>`
 to this
 `<h4><a class="color-secondary"><span class="resource-label upperC">{{localize (concat
        'FALLOUT.SKILL.' item.name)}}
      </span>`

in character sheet all skils will be transalted to local language, but it need as well change in css due to different world length, but this is jus cosmetic

**Comment by superseva** [comment]
v 11.0.2 update
