### ISSUE TITLE
Critical failure and Critical success

### ISSUE THREAD

**Issue by llothos** [superseva/fallout#8]
Not sure if this is a issue or not but I've noticed if I have a critical failure and success it cancels one of the successes out. I was using the big guns skill as a tag skill and rolled under my TN and got a 20 as well and it only counted as one success instead of two. I tried looking in the core book but couldn't see a reference to critical failure cancelling success. I could be missing something in the rules maybe.

**Comment by superseva** [comment]
I will take a look in t it. Thanks for reporting it

**Comment by superseva** [comment]
there is nothing in the code that decrease the success number, so probably the crit was not registered correctly. Still investigating

**Comment by superseva** [comment]
can't reproduce
