### ISSUE TITLE
Compendium Issue

### ISSUE THREAD

**Issue by WyntherKnight** [superseva/fallout#9]
Hi, 

I've been creating my own compendium for the fallout game and I noticed that the information in the Effects box of the item "Books and Magazines" does not get carried over to and from the compendium, it somehow gets erased. I have already created items for  Ammo, Apparel & mods. consumables (food, beverages, chems, others), Perks, Robot armor and mods, Weapons and mods and none of them show this issue. 

I also noticed that when the magazine is on the player token and the magazine's name is clicked, it will show the information on the "Description" tab instead of the one in the Effects box. Tested with a Consumable item and the information in the Effects box shows, not the description.

**Comment by superseva** [comment]
Thanks for reporting it. I'll look in to it.

**Comment by superseva** [comment]
Should be fixed now (version 1.4)
